worker_processes 1;
error_log /var/log/nginx/error.log debug;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;

    log_format debug_format
        '$remote_addr - $request '
        'URI="$request_uri" '
        'UPSTREAM="$upstream_addr" '
        'UPSTREAM_STATUS="$upstream_status" '
        'STATUS="$status"';

    server {
        listen 8080;
        server_name localhost;

        access_log /var/log/nginx/access.log debug_format;

        # FRONTEND
        location / {
            alias /var/www/deployment-lce/static/;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # BACKEND
        location /v1/ {
            proxy_pass http://127.0.0.1:9000;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
